/**
 * Demo-data script: seed a follow-up example on the demo case so the
 * follow-up structure can be inspected without clicking through the whole
 * refer flow. Uses the app's real functions only (no raw SQL inserts):
 *   insertReferralDraft → markReferralSent → recordProviderResponse →
 *   draftFollowUpText (real LLM) → storeFollowUpDraft
 *
 * Idempotent: if the case already has an open referral to Bright Path,
 * nothing is created. Run with: npm run db:demo:followup
 */
import { and, desc, eq, inArray } from "drizzle-orm";
import { db } from "./index";
import { cases, caseContexts, referrals, services } from "./schema";
import { insertReferralDraft, markReferralSent } from "../lib/refer";
import {
  buildFollowUpDraftInput,
  draftFollowUpText,
  getReferralEvents,
  recordProviderResponse,
  storeFollowUpDraft,
} from "../lib/followup";

const SERVICE_NAME = "Bright Path Financial Counselling";
const REFERRAL_TEXT = `Hello Bright Path team,

I am referring a woman I am supporting at Lou's Place (case ref CASE-2026-001). She is escaping domestic and family violence and needs free financial counselling, especially around debts and casual-income budgeting.

Key context (shared with her consent): two children (5 and 8), low income from casual part-time work, bridging visa E, communicates well in English and Arabic.

Safe contact: SMS only to her second phone — please do NOT call her main number.

Could you let me know whether you can take this referral and what the next step would be? Happy to provide more information.

Kind regards,
Caseworker, Lou's Place`;

async function main() {
  const [caseRow] = await db.select().from(cases).where(eq(cases.clientRef, "CASE-2026-001"));
  if (!caseRow) throw new Error("demo case CASE-2026-001 not found");
  const [context] = await db
    .select()
    .from(caseContexts)
    .where(eq(caseContexts.caseId, caseRow.id))
    .orderBy(desc(caseContexts.version))
    .limit(1);
  if (!context) throw new Error("no case context found for the demo case");

  const [service] = await db.select().from(services).where(eq(services.name, SERVICE_NAME));
  if (!service) throw new Error(`service "${SERVICE_NAME}" not found`);

  const existing = await db
    .select({ id: referrals.id })
    .from(referrals)
    .where(
      and(
        eq(referrals.caseId, caseRow.id),
        eq(referrals.serviceId, service.id),
        inArray(referrals.status, ["sent", "responded"]),
      ),
    );
  if (existing.length > 0) {
    console.log("Open referral to Bright Path already exists — nothing to do.");
    return;
  }

  // 1) draft referral → mark sent, follow-up due today (shows on the dashboard)
  const referralId = await insertReferralDraft({
    caseId: caseRow.id,
    contextId: context.id,
    serviceId: service.id,
    draftText: REFERRAL_TEXT,
    sharedFields: ["needs", "children", "income", "visa", "languages", "safe_contact_method"],
  });
  const due = new Date().toISOString().slice(0, 10);
  const sent = await markReferralSent(referralId, due);
  if (!sent) throw new Error("markReferralSent failed");
  console.log(`Referral to ${service.name} created + sent (due ${due}).`);

  // 2) a recorded provider response (status sent → responded, timeline entry)
  await recordProviderResponse(
    referralId,
    "Intake worker Maya called back — offered a free phone financial-counselling session next week. Asked us to SMS the client to confirm a time that suits.",
  );
  console.log("Provider response recorded (referral now responded).");

  // 3) LLM-drafted follow-up message for worker review (nothing transmitted)
  const events = await getReferralEvents(referralId);
  const input = buildFollowUpDraftInput(
    {
      serviceName: service.name,
      clientRef: caseRow.clientRef,
      sentAt: new Date(),
      draftText: REFERRAL_TEXT,
      status: "responded",
      outcome: null,
    },
    events,
  );
  const draft = await draftFollowUpText(input);
  const stored = await storeFollowUpDraft(referralId, draft);
  if (!stored) throw new Error("storeFollowUpDraft failed");
  console.log("Follow-up draft generated by the LLM and stored on the timeline:\n");
  console.log(draft);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
